<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.10.0" />
    <PackageReference Include="Microsoft.Build" Version="17.9.5" />
    <PackageReference Include="Microsoft.Build.Framework" Version="17.9.5" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.9.5" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.6.10" />
    <PackageReference Include="Parquet.Net" Version="4.18.0" />
  </ItemGroup>
</Project>
